\documentclass[a4paper,english,10pt]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\usepackage{cite}
\usepackage{color} 
\usepackage{float}
\usepackage{longtable}
\usepackage[bottom]{footmisc}
\usepackage{url}
\usepackage{natbib}
\usepackage{authblk}
\usepackage[T1]{fontenc}
\usepackage[utf8x]{inputenc}
\usepackage{babel}
\usepackage{hyperref}
\usepackage{geometry}
\geometry{verbose,a4paper,tmargin=3cm,bmargin=2cm,lmargin=2cm,rmargin=3cm}
\setlength{\parskip}{\medskipamount}
\setlength{\parindent}{0pt}
\hypersetup{
    colorlinks=true,       % false: boxed links; true: colored links
    linkcolor=blue,        % color of internal links
    citecolor=red,         % color of links to bibliography
    filecolor=blue,        % color of file links
    urlcolor=blue          % color of external links
}

% Define some handy formatting
\newcommand{\code}[1]{{\texttt{#1}}}
\newcommand{\pkg}[1]{{\texttt{#1}}}
\newcommand{\class}[1]{{\textit{#1}}}
\newcommand{\R}{{\normalfont\textsf{R }}{}}
\newcommand{\args}[1]{{\texttt{#1}}}

%----------------------------------------------------------------------------------

\begin{document}
%\SweaveOpts{concordance=TRUE}

\title{a4a stock assessment framework \\ DRAFT}

\author[1]{Ernesto Jardim}
\author[1]{Colin Millar}
\author[1]{Finlay Scott}
\affil[1]{European Commission, Joint Research Centre, IPSC / Maritime Affairs Unit, 21027 Ispra (VA), Italy}
\affil[*]{Corresponding author \href{mailto:ernesto.jardim@jrc.ec.europa.eu}{ernesto.jardim@jrc.ec.europa.eu}}

\maketitle
\tableofcontents
\newpage

\section{Running assessments}

There are two basic types of assessments available from using \texttt{a4a}: the management procedure (MP) fit and the full assessment fit.  The MP fit does not compute estimates of covariances and is therefore quicker to execute, while the full assessment fit returns parameter estimates and their covariances and hence retains the ability to simulate from the model at the expense of longer fitting time.

In the \texttt{a4a} assessment model, the model structure is defined by submodels.  These are models for the different parts of a statistical catch at age model that requires structural assumptions, such as the selectivity of the fishing fleet, or how F-at-age changes over time.  It is advantageous to write the model for F-at-age and survey catchability as linear models (by working with log F and log Q) becuase it allows us to use the linear modelling tools available in R:  see for example gam formulas, or factorial design formulas using lm.  In R's linear modelling lanquage, a constant model is coded as $\sim$ 1, while a slope over age would simply be $\sim$ age.  Extending this we can write a traditional year / age seperable F model like $\sim$ factor(age) $+$ factor(year).

There are effectively 5 submodels in operation: the model for F-at-age, a model for initial age structure, a model for recruitment, a (list) of model(s) for survey catchability-at-age, and a list of models for the observation variance of catch.n and the survey indices.  In practice, we fix the variance models and the initial age structure models, but in theory these can be changed.  A basic set of submodels would be

<<>>=
fmodel <- ~ factor(age) + factor(year)
qmodel <- list(~ factor(age)) 
@

<<>>=
library(FLa4a)
library(diagram)
data(ple4)
data(ple4.indices)
source("funs.R")
@

\subsection{Quick and dirty}

The default settings of the stock assessment model work reasoably well. It's an area of research that will improve with time.

<<>>=
data(ple4)
data(ple4.indices)
fit <- sca(ple4, ple4.indices)
@

Note that because the survey index for plaice has missing values we get a warning saying that we assume these values are missing at random, and not because the observations were zero.

<<>>=
res <- residuals(fit, ple4, ple4.indices)
@

<<figure=TRUE>>=
plot(res, main="Residuals")
@

<<figure=TRUE>>=
bubbles(res)
@

<<figure=TRUE>>=
qqmath(res)
@

We can inspect the summaries from this fit my adding it to the origional stock object, for example to see the fitted fbar we can do

<<figure=TRUE>>=
stk <- ple4 + fit
plot(stk, main="Stock summary")
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(stk)), drape = TRUE, main="Fishing mortality", screen = list(x = -90, y=-45))
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(stock.n(stk)), drape = TRUE, main="Population", screen = list(x = -90, y=-45))
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(catch.n(stk)), drape = TRUE, main="Catches")
@

\subsection{Data structures}

The basic model output is contained in the \texttt{a4aFit} class. This object contains only the fitted values.

<<>>=
showClass("a4aFit")
@

<<figure=TRUE>>=
plotS4("a4aFit", main="a4aFit class", lwd = 1, box.lwd = 2, cex.txt = 0.8, box.size = 0.1, box.type = "square", box.prop = 0.3)
@

Fitted values are stored in the \texttt{stock.n}, \texttt{harvest}, \texttt{catch.n} and \texttt{index} slots.  It also contains information carried over from the stock object used to fit the model: the name of the stock in \texttt{name}, any description provided in \texttt{desc} and the age and year range and mean F range in \texttt{range}.  There is also a wall clock that has a breakdown of the time taken o run the model.

The full assessment fit returns an object of \texttt{a4aFitSA} class:

<<>>=
showClass("a4aFitSA")
@

<<figure=TRUE>>=
plotS4("a4aFitSA", main="a4aFitSA class", lwd = 1, box.lwd = 2, cex.txt = 0.8, box.size = 0.1, box.type = "square", box.prop = 0.3)
@

The additional slots in the assessment output is the \texttt{fitSumm} and \texttt{pars} slots which are containers for model summaries and the model parameters.  The \texttt{pars} slot is a class of type \texttt{SCAPars} which is itself composed of sub-classes, designed to contain the information necessary to simulate from the model.

<<>>=
showClass("SCAPars")
showClass("a4aStkParams")
showClass("submodel")
@

<<figure=TRUE>>=
plotS4("SCAPars", main="SCAPars class", lwd = 1, box.lwd = 2, cex.txt = 0.8, box.size = 0.1, box.type = "square", box.prop = 0.3)
@

<<figure=TRUE>>=
plotS4("a4aStkParams", main="a4aStkParams class", lwd = 1, box.lwd = 2, cex.txt = 0.8, box.size = 0.1, box.type = "square", box.prop = 0.3)
@

<<figure=TRUE>>=
plotS4("submodel", main="submodel class", lwd = 1, box.lwd = 2, cex.txt = 0.8, box.size = 0.1, box.type = "square", box.prop = 0.3)
@

for example, all the parameters required so simulate a time-series of mean F trends is contained in the \texttt{stkmodel} slot, which is a class of type \texttt{a4aStkParams}.  This class contains the relevant submodels (see later), their parameters \texttt{params} and the joint covariance matrix \texttt{vcov} for all stock related parameters.

\subsection{The sca method - statistical catch-at-age}

We will now take a look at some examples for F models and the forms that we can get.  Lets start with a separable model in which we model selectivity at age as an (unpenalised) thin plate spline.  We will use the North Sea Plaice data again, and since this has 10 ages we will use a simple rule of thumb that the spline should have fewer than $\frac{10}{2} = 5$ degrees of freedom, and so we opt for 4 degrees of freedom.  We will also do the same for year and model the change in F through time as a smoother with 20 degrees of freedom.

Lets now investigate some variations in the selectivity shape with time, but only a little... we can do this by adding a smooth interaction term in the fmodel

A further move is to free up the Fs to vary more over time

In the last examples the Fs are linked across age and time.  What if we want to free up a specific age class because in the residuals we see a consistent pattern.  This can happen, for example, if the spatial distribution of juvenilles is disconnected to the distribution of adults.  The fishery focuses on the adult fish, and therefore the the F on young fish is a function of the distribution of the juveniles and could deserve a seperate model.  This can be achieved by

Please note that each of these model \emph{structures} lets say, have not been tuned to the data.  The degrees of freedom of each model can be better tuned to the data by using model selection procedures such as AIC or BIC.

\subsubsection{Fishing mortality submodel}

<<>>=
qmodel <- list(~ factor(age)) 
fmodel <- ~ factor(age) + factor(year)
fit <- sca(stock = ple4, indices = ple4.indices[1], fmodel=fmodel, qmodel=qmodel)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(fit)), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20)
fit1 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(fit1)), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20) + te(age, year, k = c(3,3))
fit2 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(fit2)), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
fmodel <- ~ te(age, year, k = c(4,20))
fit3 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(fit3)), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
fmodel <- ~ te(age, year, k = c(4,20)) + s(year, k = 5, by = as.numeric(age==1))
fit4 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(harvest(fit4)), drape = TRUE, screen = list(x = -90, y=-45))
@

\subsubsection{Catchability submodel}

<<>>=
sfrac <- mean(range(ple4.indices[[1]])[c("startf", "endf")])
fmodel <- ~ factor(age) + factor(year)
@

<<>>=
qmodel <- list(~ factor(age)) 
fit <- sca(ple4, ple4.indices[1], fmodel, qmodel)
Z <- m(ple4) + harvest(fit)*sfrac
lst <- dimnames(fit@index[[1]])
lst$x <- stock.n(fit)*exp(-Z)
stkn <- do.call("trim", lst)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(index(fit)[[1]]/stkn), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
qmodel <- list(~ s(age, k=4))
fit1 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
Z <- m(ple4) + harvest(fit1)*sfrac
lst <- dimnames(fit1@index[[1]])
lst$x <- stock.n(fit1)*exp(-Z)
stkn <- do.call("trim", lst)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(index(fit1)[[1]]/stkn), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
qmodel <- list(~ te(age, year, k = c(3,40)))
fit2 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
Z <- m(ple4) + harvest(fit2)*sfrac
lst <- dimnames(fit2@index[[1]])
lst$x <- stock.n(fit2)*exp(-Z)
stkn <- do.call("trim", lst)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(index(fit2)[[1]]/stkn), drape = TRUE, screen = list(x = -90, y=-45))
@

<<>>=
qmodel <- list( ~ s(age, k=4) + year)
fit3 <- sca(ple4, ple4.indices[1], fmodel, qmodel)
Z <- m(ple4) + harvest(fit3)*sfrac
lst <- dimnames(fit3@index[[1]])
lst$x <- stock.n(fit3)*exp(-Z)
stkn <- do.call("trim", lst)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(index(fit3)[[1]]/stkn), drape = TRUE, screen = list(x = -90, y=-45))
@

\subsubsection{Stock-recruitment submodel}

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20)
qmodel <- list(~ s(age, k=4))
@

<<>>=
srmodel <- ~ factor(year)
fit <- sca(ple4, ple4.indices[1], fmodel=fmodel, qmodel=qmodel, srmodel=srmodel) 
srmodel <- ~ s(year, k=20)
fit1 <- sca(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
srmodel <- ~ ricker(CV=0.05)
fit2 <- sca(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
srmodel <- ~ bevholt(CV=0.05)
fit3 <- sca(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
srmodel <- ~ hockey(CV=0.05)
fit4 <- sca(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
srmodel <- ~ geomean(CV=0.05)
fit5 <- sca(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
flqs <- FLQuants(fac=stock.n(fit)[1], smo=stock.n(fit1)[1], ric=stock.n(fit2)[1], bh=stock.n(fit3)[1], hs=stock.n(fit4)[1], gm=stock.n(fit5)[1])
@

<<figure=TRUE>>=
xyplot(data~year, groups=qname, data=flqs, type="l", main="Recruitment models", auto.key=list(points=FALSE, lines=TRUE, columns=3))
@

\subsection{The a4aSCA method - advanced features}

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20)
qmodel <- list( ~ s(age, k=4) + year)
srmodel <- ~s(year, k=20)
fit <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
@

\subsubsection{N1 model}

<<>>=
n1model <- ~s(age, k=4)
fit1 <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel, n1model) 
flqs <- FLQuants(smo=stock.n(fit1)[,1], fac=stock.n(fit)[,1])
@

<<figure=TRUE>>=
xyplot(data~age, groups=qname, data=flqs, type="l", main="N1 models", auto.key=list(points=FALSE, lines=TRUE, columns=2))
@

\subsubsection{Variance model}

One important subject related with fisheries data used for input to stock assessment models is the shape of the variance of the data. It's quite common to have more precision on the most represented ages and less precision on the less frequent ages. Due to the fact that the last do not show so often on the auction markets, on the fishing operations or on survey samples.

By default the model assumes constant variance over time and ages (~ 1 model) but it can use other models specified by the user. This feature requires a call to the a4aInternal method, which gives more options than the a4a method, which in fact is a wrapper.

<<>>=
vmodel <- list(~1, ~1)
fit <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel, n1model, vmodel) 
vmodel <- list(~ s(age, k=4), ~1)
fit1 <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel, n1model, vmodel) 
flqs <- FLQuants(cts=catch.n(fit), smo=catch.n(fit1))
@

<<figure=TRUE>>=
xyplot(data~year|age, groups=qname, data=flqs, type="l", main="Variance models", scales=list(y=list(relation="free")), auto.key=list(points=FALSE, lines=TRUE, columns=2))
@

\subsubsection{External weigthing of likelihood components}

By default the likelihood components are weighted using inverse variance of the parameters estimates. However the user may change this weights by setting the variance of the input parameters, which is done by adding a variance matrix to the catch.n and index.n slots of the stock and index objects. 

<<>>=
stk <- ple4
idx <- ple4.indices[1]
# variance of observed catches
varslt <- catch.n(stk)
varslt[] <- 1
catch.n(stk) <- FLQuantDistr(catch.n(stk), varslt)
# variance of observed indices
varslt <- index(idx[[1]])
varslt[] <- 0.05
index.var(idx[[1]]) <- varslt
# run
fit1 <- a4aSCA(stk, idx, fmodel, qmodel, srmodel, n1model, vmodel=list(~1, ~1)) 
flqs <- FLQuants(nowgt=stock.n(fit), extwgt=stock.n(fit1))
@

<<figure=TRUE>>=
xyplot(data~year|age, groups=qname, data=flqs, type="l", main="Likelihood weighting", scales=list(y=list(relation="free")), auto.key=list(points=FALSE, lines=TRUE, columns=2))
@

\subsubsection{Assessing ADMB files}

To inspect the ADMB files the user must specify the working dir and all files will be left there.

<<>>=
fit1 <- a4aSCA(stk, idx, fmodel, qmodel, srmodel, n1model, vmodel=list(~1, ~1), wkdir="mytest") 
@

\subsection{Predict and simulate}

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20)
qmodel <- list( ~ s(age, k=4) + year)
srmodel <- ~s(year, k=20)
fit <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
@

\subsubsection{Predict}

<<>>=
fit.pred <- predict(fit)
lapply(fit.pred, names)
@

\subsubsection{simulate}

<<>>=
fits <- simulate(fit, 1000)
flqs <- FLQuants(sim=iterMedians(stock.n(fits)), det=stock.n(fit))
@

<<figure=TRUE>>=
xyplot(data~year|age, groups=qname, data=flqs, type="l", main="Median simulations VS fit", scales=list(y=list(relation="free")))
@

<<figure=TRUE>>=
stks <- ple4 + fits
plot(stks)
@

\subsubsection{Working with covariates}

<<>>=
nao <- read.table("http://www.cdc.noaa.gov/data/correlation/nao.data", skip=1, nrow=62, na.strings="-99.90")
dnms <- list(quant="nao", year=1948:2009, unit="unique", season=1:12, area="unique")
nao <- FLQuant(unlist(nao[,-1]), dimnames=dnms, units="nao")
nao <- seasonMeans(trim(nao, year=dimnames(stock.n(ple4))$year))
nao <- as.numeric(nao)
@

<<>>=
srmodel <- ~ nao
fit2 <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
flqs <- FLQuants(fac=stock.n(fit)[1], cvar=stock.n(fit2)[1])
@

<<figure=TRUE>>=
xyplot(data~year, groups=qname, data=flqs, type="l", main="Recruitment model with covariates")
@

<<figure=TRUE>>=
srmodel <- ~ ricker(a=~nao, CV=0.1)
fit3 <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
flqs <- FLQuants(fac=stock.n(fit)[1], cvar=stock.n(fit3)[1])
@

<<figure=TRUE>>=
xyplot(data~year, groups=qname, data=flqs, type="l", main="Recruitment model with covariates")
@

<<>>=
srmodel <- ~s(year, k=20)
qmodel <- list(~ factor(age) + nao)
fit4 <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel, covar=list(nao=nao)) 
flqs <- FLQuants(smo=stock.n(fit), cvar=stock.n(fit4))
@

<<figure=TRUE>>=
xyplot(data~year|age, groups=qname, data=flqs, type="l", main="Catchability model with covariates", scales=list(y=list(relation="free")))
@

<<>>=
Z <- m(ple4) + harvest(fit4)*sfrac
lst <- dimnames(fit@index[[1]])
lst$x <- stock.n(fit4)*exp(-Z)
stkn <- do.call("trim", lst)
@

<<figure=TRUE>>=
wireframe(data ~ age + year, data = as.data.frame(index(fit4)[[1]]/stkn), drape = TRUE, screen = list(x = -90, y=-45))
@

\subsection{Geeky stuff}

<<>>=
fmodel <- ~ s(age, k=4) + s(year, k = 20)
qmodel <- list( ~ s(age, k=4) + year)
srmodel <- ~s(year, k=20)
fit <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
@

\subsubsection{WCSAM exercise - replicating itself}

<<>>=
fits <- simulate(fit, 25)
stks <- ple4 + fits
fit1 <- a4aSCA(stks, idxs, fmodel, qmodel, srmodel, fit="MP") 
@

<<figure=TRUE>>=
plot(FLStocks(sim=ple4 + fit1, orig=ple4+fit))
@

\subsubsection{Likelihood profiling - ToDo}

<<>>=
#ks <- seq(10,50,5)
#qmodel <- list( ~ s(age, k=4) + year)
#srmodel <- ~s(year, k=20)
#liks <- liks <- data.frame(k=ks, nlogl=NA)
#for(i in ks){
#	fmodel <- as.formula(substitute(~s(age, k=4) + s(year, k=x), list(x=i)))
#	liks[liks$k==i,2] <- as.numeric(BIC(a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel)))
#}
@

\subsubsection{Paralell computing (not working yet ...)}

<<>>=
#fmodel <- ~ s(age, k=4) + s(year, k = 20)
#qmodel <- list( ~ s(age, k=4) + year)
#srmodel <- ~s(year, k=20)
#fit <- a4aSCA(ple4, ple4.indices[1], fmodel, qmodel, srmodel) 
#fits <- simulate(fit, 25)
#stks <- ple4 + fits 
#idxs <- ple4.indices[1]
#index(idxs[[1]]) <- index(fits)[[1]]
#library(parallel)
#options(mc.cores=1)
#lst <- mclapply(split(1:25, 1:25), function(x){
#	fit <- a4aSCA(stks[,,,,,x], FLIndices(idxs[[1]][,,,,,x]), fmodel, qmodel, srmodel, fit="MP") 
#})
@

\end{document}

